 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.gate.global;
import protocol.msgId.Id;
public class G2GMIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(G2GM.MSG_GM2G_REQ_Register.class, 0x210001);
     }
}
