 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.zone.relation;
import protocol.msgId.Id;
public class Z2RIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.zone.relation.Z2R.MSG_Z2R_HEARTBEAT.class, 0x450001);
     }
}
