// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2G.proto

package protocol.client.c2g;

public final class C2G {
  private C2G() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MSG_CG_USER_LOGINOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.client.c2g.MSG_CG_USER_LOGIN)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string accountName = 1;</code>
     */
    boolean hasAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    String getAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>required int32 token = 2;</code>
     */
    boolean hasToken();
    /**
     * <code>required int32 token = 2;</code>
     */
    int getToken();

    /**
     * <code>required string version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 3;</code>
     */
    String getVersion();
    /**
     * <code>required string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>required string deviceId = 4;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string deviceId = 4;</code>
     */
    String getDeviceId();
    /**
     * <code>required string deviceId = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>required int32 mainId = 5;</code>
     */
    boolean hasMainId();
    /**
     * <code>required int32 mainId = 5;</code>
     */
    int getMainId();

    /**
     * <code>required string registerId = 7;</code>
     */
    boolean hasRegisterId();
    /**
     * <code>required string registerId = 7;</code>
     */
    String getRegisterId();
    /**
     * <code>required string registerId = 7;</code>
     */
    com.google.protobuf.ByteString
        getRegisterIdBytes();

    /**
     * <code>required string channelName = 8;</code>
     */
    boolean hasChannelName();
    /**
     * <code>required string channelName = 8;</code>
     */
    String getChannelName();
    /**
     * <code>required string channelName = 8;</code>
     */
    com.google.protobuf.ByteString
        getChannelNameBytes();
  }
  /**
   * Protobuf type {@code protocol.client.c2g.MSG_CG_USER_LOGIN}
   */
  public  static final class MSG_CG_USER_LOGIN extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.client.c2g.MSG_CG_USER_LOGIN)
      MSG_CG_USER_LOGINOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_CG_USER_LOGIN.newBuilder() to construct.
    private MSG_CG_USER_LOGIN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_CG_USER_LOGIN() {
      accountName_ = "";
      token_ = 0;
      version_ = "";
      deviceId_ = "";
      mainId_ = 0;
      registerId_ = "";
      channelName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_CG_USER_LOGIN(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              accountName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              token_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              version_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              deviceId_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mainId_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              registerId_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              channelName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return C2G.internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return C2G.internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_CG_USER_LOGIN.class, Builder.class);
    }

    private int bitField0_;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private volatile Object accountName_;
    /**
     * <code>required string accountName = 1;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public String getAccountName() {
      Object ref = accountName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private int token_;
    /**
     * <code>required int32 token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 token = 2;</code>
     */
    public int getToken() {
      return token_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile Object version_;
    /**
     * <code>required string version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string version = 3;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 4;
    private volatile Object deviceId_;
    /**
     * <code>required string deviceId = 4;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string deviceId = 4;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINID_FIELD_NUMBER = 5;
    private int mainId_;
    /**
     * <code>required int32 mainId = 5;</code>
     */
    public boolean hasMainId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 mainId = 5;</code>
     */
    public int getMainId() {
      return mainId_;
    }

    public static final int REGISTERID_FIELD_NUMBER = 7;
    private volatile Object registerId_;
    /**
     * <code>required string registerId = 7;</code>
     */
    public boolean hasRegisterId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string registerId = 7;</code>
     */
    public String getRegisterId() {
      Object ref = registerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          registerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string registerId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRegisterIdBytes() {
      Object ref = registerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        registerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELNAME_FIELD_NUMBER = 8;
    private volatile Object channelName_;
    /**
     * <code>required string channelName = 8;</code>
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string channelName = 8;</code>
     */
    public String getChannelName() {
      Object ref = channelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      Object ref = channelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccountName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMainId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRegisterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, mainId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, registerId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, channelName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mainId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, registerId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, channelName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_CG_USER_LOGIN)) {
        return super.equals(obj);
      }
      MSG_CG_USER_LOGIN other = (MSG_CG_USER_LOGIN) obj;

      boolean result = true;
      result = result && (hasAccountName() == other.hasAccountName());
      if (hasAccountName()) {
        result = result && getAccountName()
            .equals(other.getAccountName());
      }
      result = result && (hasToken() == other.hasToken());
      if (hasToken()) {
        result = result && (getToken()
            == other.getToken());
      }
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && getVersion()
            .equals(other.getVersion());
      }
      result = result && (hasDeviceId() == other.hasDeviceId());
      if (hasDeviceId()) {
        result = result && getDeviceId()
            .equals(other.getDeviceId());
      }
      result = result && (hasMainId() == other.hasMainId());
      if (hasMainId()) {
        result = result && (getMainId()
            == other.getMainId());
      }
      result = result && (hasRegisterId() == other.hasRegisterId());
      if (hasRegisterId()) {
        result = result && getRegisterId()
            .equals(other.getRegisterId());
      }
      result = result && (hasChannelName() == other.hasChannelName());
      if (hasChannelName()) {
        result = result && getChannelName()
            .equals(other.getChannelName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAccountName()) {
        hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getAccountName().hashCode();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      if (hasDeviceId()) {
        hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceId().hashCode();
      }
      if (hasMainId()) {
        hash = (37 * hash) + MAINID_FIELD_NUMBER;
        hash = (53 * hash) + getMainId();
      }
      if (hasRegisterId()) {
        hash = (37 * hash) + REGISTERID_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterId().hashCode();
      }
      if (hasChannelName()) {
        hash = (37 * hash) + CHANNELNAME_FIELD_NUMBER;
        hash = (53 * hash) + getChannelName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_CG_USER_LOGIN parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_USER_LOGIN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_USER_LOGIN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_CG_USER_LOGIN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_CG_USER_LOGIN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_CG_USER_LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_CG_USER_LOGIN prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.client.c2g.MSG_CG_USER_LOGIN}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.client.c2g.MSG_CG_USER_LOGIN)
        MSG_CG_USER_LOGINOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_CG_USER_LOGIN.class, Builder.class);
      }

      // Construct using protocol.client.c2g.C2G.MSG_CG_USER_LOGIN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        mainId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        registerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        channelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor;
      }

      public MSG_CG_USER_LOGIN getDefaultInstanceForType() {
        return MSG_CG_USER_LOGIN.getDefaultInstance();
      }

      public MSG_CG_USER_LOGIN build() {
        MSG_CG_USER_LOGIN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_CG_USER_LOGIN buildPartial() {
        MSG_CG_USER_LOGIN result = new MSG_CG_USER_LOGIN(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mainId_ = mainId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.registerId_ = registerId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.channelName_ = channelName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_CG_USER_LOGIN) {
          return mergeFrom((MSG_CG_USER_LOGIN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_CG_USER_LOGIN other) {
        if (other == MSG_CG_USER_LOGIN.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000001;
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000008;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasMainId()) {
          setMainId(other.getMainId());
        }
        if (other.hasRegisterId()) {
          bitField0_ |= 0x00000020;
          registerId_ = other.registerId_;
          onChanged();
        }
        if (other.hasChannelName()) {
          bitField0_ |= 0x00000040;
          channelName_ = other.channelName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountName()) {
          return false;
        }
        if (!hasToken()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        if (!hasDeviceId()) {
          return false;
        }
        if (!hasMainId()) {
          return false;
        }
        if (!hasRegisterId()) {
          return false;
        }
        if (!hasChannelName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_CG_USER_LOGIN parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_CG_USER_LOGIN) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object accountName_ = "";
      /**
       * <code>required string accountName = 1;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public String getAccountName() {
        Object ref = accountName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accountName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }

      private int token_ ;
      /**
       * <code>required int32 token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public int getToken() {
        return token_;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder setToken(int value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = 0;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>required string version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string version = 3;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 3;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>required string deviceId = 4;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string deviceId = 4;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceId = 4;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 4;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 4;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int mainId_ ;
      /**
       * <code>required int32 mainId = 5;</code>
       */
      public boolean hasMainId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 mainId = 5;</code>
       */
      public int getMainId() {
        return mainId_;
      }
      /**
       * <code>required int32 mainId = 5;</code>
       */
      public Builder setMainId(int value) {
        bitField0_ |= 0x00000010;
        mainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mainId = 5;</code>
       */
      public Builder clearMainId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mainId_ = 0;
        onChanged();
        return this;
      }

      private Object registerId_ = "";
      /**
       * <code>required string registerId = 7;</code>
       */
      public boolean hasRegisterId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string registerId = 7;</code>
       */
      public String getRegisterId() {
        Object ref = registerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            registerId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string registerId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRegisterIdBytes() {
        Object ref = registerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          registerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string registerId = 7;</code>
       */
      public Builder setRegisterId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        registerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string registerId = 7;</code>
       */
      public Builder clearRegisterId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        registerId_ = getDefaultInstance().getRegisterId();
        onChanged();
        return this;
      }
      /**
       * <code>required string registerId = 7;</code>
       */
      public Builder setRegisterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        registerId_ = value;
        onChanged();
        return this;
      }

      private Object channelName_ = "";
      /**
       * <code>required string channelName = 8;</code>
       */
      public boolean hasChannelName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string channelName = 8;</code>
       */
      public String getChannelName() {
        Object ref = channelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string channelName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getChannelNameBytes() {
        Object ref = channelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelName = 8;</code>
       */
      public Builder setChannelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        channelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 8;</code>
       */
      public Builder clearChannelName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        channelName_ = getDefaultInstance().getChannelName();
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 8;</code>
       */
      public Builder setChannelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        channelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.client.c2g.MSG_CG_USER_LOGIN)
    }

    // @@protoc_insertion_point(class_scope:protocol.client.c2g.MSG_CG_USER_LOGIN)
    private static final MSG_CG_USER_LOGIN DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_CG_USER_LOGIN();
    }

    public static MSG_CG_USER_LOGIN getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_CG_USER_LOGIN>
        PARSER = new com.google.protobuf.AbstractParser<MSG_CG_USER_LOGIN>() {
      public MSG_CG_USER_LOGIN parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_CG_USER_LOGIN(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_CG_USER_LOGIN> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_CG_USER_LOGIN> getParserForType() {
      return PARSER;
    }

    public MSG_CG_USER_LOGIN getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MSG_CG_CREATE_CHARACTEROrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.client.c2g.MSG_CG_CREATE_CHARACTER)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 mainId = 2;</code>
     */
    boolean hasMainId();
    /**
     * <code>required int32 mainId = 2;</code>
     */
    int getMainId();

    /**
     * <code>required int32 sex = 3;</code>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 3;</code>
     */
    int getSex();

    /**
     * <code>required int32 head = 4;</code>
     */
    boolean hasHead();
    /**
     * <code>required int32 head = 4;</code>
     */
    int getHead();

    /**
     * <code>required int32 systemFashionId = 5;</code>
     */
    boolean hasSystemFashionId();
    /**
     * <code>required int32 systemFashionId = 5;</code>
     */
    int getSystemFashionId();
  }
  /**
   * Protobuf type {@code protocol.client.c2g.MSG_CG_CREATE_CHARACTER}
   */
  public  static final class MSG_CG_CREATE_CHARACTER extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.client.c2g.MSG_CG_CREATE_CHARACTER)
      MSG_CG_CREATE_CHARACTEROrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_CG_CREATE_CHARACTER.newBuilder() to construct.
    private MSG_CG_CREATE_CHARACTER(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_CG_CREATE_CHARACTER() {
      name_ = "";
      mainId_ = 0;
      sex_ = 0;
      head_ = 0;
      systemFashionId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_CG_CREATE_CHARACTER(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              mainId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              head_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              systemFashionId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return C2G.internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return C2G.internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_CG_CREATE_CHARACTER.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINID_FIELD_NUMBER = 2;
    private int mainId_;
    /**
     * <code>required int32 mainId = 2;</code>
     */
    public boolean hasMainId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 mainId = 2;</code>
     */
    public int getMainId() {
      return mainId_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>required int32 sex = 3;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int HEAD_FIELD_NUMBER = 4;
    private int head_;
    /**
     * <code>required int32 head = 4;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 head = 4;</code>
     */
    public int getHead() {
      return head_;
    }

    public static final int SYSTEMFASHIONID_FIELD_NUMBER = 5;
    private int systemFashionId_;
    /**
     * <code>required int32 systemFashionId = 5;</code>
     */
    public boolean hasSystemFashionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 systemFashionId = 5;</code>
     */
    public int getSystemFashionId() {
      return systemFashionId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMainId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSystemFashionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, mainId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, head_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, systemFashionId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, mainId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, head_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, systemFashionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_CG_CREATE_CHARACTER)) {
        return super.equals(obj);
      }
      MSG_CG_CREATE_CHARACTER other = (MSG_CG_CREATE_CHARACTER) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasMainId() == other.hasMainId());
      if (hasMainId()) {
        result = result && (getMainId()
            == other.getMainId());
      }
      result = result && (hasSex() == other.hasSex());
      if (hasSex()) {
        result = result && (getSex()
            == other.getSex());
      }
      result = result && (hasHead() == other.hasHead());
      if (hasHead()) {
        result = result && (getHead()
            == other.getHead());
      }
      result = result && (hasSystemFashionId() == other.hasSystemFashionId());
      if (hasSystemFashionId()) {
        result = result && (getSystemFashionId()
            == other.getSystemFashionId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasMainId()) {
        hash = (37 * hash) + MAINID_FIELD_NUMBER;
        hash = (53 * hash) + getMainId();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex();
      }
      if (hasHead()) {
        hash = (37 * hash) + HEAD_FIELD_NUMBER;
        hash = (53 * hash) + getHead();
      }
      if (hasSystemFashionId()) {
        hash = (37 * hash) + SYSTEMFASHIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSystemFashionId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_CG_CREATE_CHARACTER parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_CG_CREATE_CHARACTER parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_CG_CREATE_CHARACTER parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_CG_CREATE_CHARACTER parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_CG_CREATE_CHARACTER prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.client.c2g.MSG_CG_CREATE_CHARACTER}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.client.c2g.MSG_CG_CREATE_CHARACTER)
        MSG_CG_CREATE_CHARACTEROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_CG_CREATE_CHARACTER.class, Builder.class);
      }

      // Construct using protocol.client.c2g.C2G.MSG_CG_CREATE_CHARACTER.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mainId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        head_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        systemFashionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return C2G.internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor;
      }

      public MSG_CG_CREATE_CHARACTER getDefaultInstanceForType() {
        return MSG_CG_CREATE_CHARACTER.getDefaultInstance();
      }

      public MSG_CG_CREATE_CHARACTER build() {
        MSG_CG_CREATE_CHARACTER result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_CG_CREATE_CHARACTER buildPartial() {
        MSG_CG_CREATE_CHARACTER result = new MSG_CG_CREATE_CHARACTER(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mainId_ = mainId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.head_ = head_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.systemFashionId_ = systemFashionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_CG_CREATE_CHARACTER) {
          return mergeFrom((MSG_CG_CREATE_CHARACTER)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_CG_CREATE_CHARACTER other) {
        if (other == MSG_CG_CREATE_CHARACTER.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMainId()) {
          setMainId(other.getMainId());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasHead()) {
          setHead(other.getHead());
        }
        if (other.hasSystemFashionId()) {
          setSystemFashionId(other.getSystemFashionId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasMainId()) {
          return false;
        }
        if (!hasSex()) {
          return false;
        }
        if (!hasHead()) {
          return false;
        }
        if (!hasSystemFashionId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_CG_CREATE_CHARACTER parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_CG_CREATE_CHARACTER) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int mainId_ ;
      /**
       * <code>required int32 mainId = 2;</code>
       */
      public boolean hasMainId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 mainId = 2;</code>
       */
      public int getMainId() {
        return mainId_;
      }
      /**
       * <code>required int32 mainId = 2;</code>
       */
      public Builder setMainId(int value) {
        bitField0_ |= 0x00000002;
        mainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mainId = 2;</code>
       */
      public Builder clearMainId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mainId_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>required int32 sex = 3;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000004;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 3;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private int head_ ;
      /**
       * <code>required int32 head = 4;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 head = 4;</code>
       */
      public int getHead() {
        return head_;
      }
      /**
       * <code>required int32 head = 4;</code>
       */
      public Builder setHead(int value) {
        bitField0_ |= 0x00000008;
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 head = 4;</code>
       */
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000008);
        head_ = 0;
        onChanged();
        return this;
      }

      private int systemFashionId_ ;
      /**
       * <code>required int32 systemFashionId = 5;</code>
       */
      public boolean hasSystemFashionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 systemFashionId = 5;</code>
       */
      public int getSystemFashionId() {
        return systemFashionId_;
      }
      /**
       * <code>required int32 systemFashionId = 5;</code>
       */
      public Builder setSystemFashionId(int value) {
        bitField0_ |= 0x00000010;
        systemFashionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 systemFashionId = 5;</code>
       */
      public Builder clearSystemFashionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        systemFashionId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.client.c2g.MSG_CG_CREATE_CHARACTER)
    }

    // @@protoc_insertion_point(class_scope:protocol.client.c2g.MSG_CG_CREATE_CHARACTER)
    private static final MSG_CG_CREATE_CHARACTER DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_CG_CREATE_CHARACTER();
    }

    public static MSG_CG_CREATE_CHARACTER getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_CG_CREATE_CHARACTER>
        PARSER = new com.google.protobuf.AbstractParser<MSG_CG_CREATE_CHARACTER>() {
      public MSG_CG_CREATE_CHARACTER parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_CG_CREATE_CHARACTER(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_CG_CREATE_CHARACTER> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_CG_CREATE_CHARACTER> getParserForType() {
      return PARSER;
    }

    public MSG_CG_CREATE_CHARACTER getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tC2G.proto\022\023protocol.client.c2g\"\223\001\n\021MSG" +
      "_CG_USER_LOGIN\022\023\n\013accountName\030\001 \002(\t\022\r\n\005t" +
      "oken\030\002 \002(\005\022\017\n\007version\030\003 \002(\t\022\020\n\010deviceId\030" +
      "\004 \002(\t\022\016\n\006mainId\030\005 \002(\005\022\022\n\nregisterId\030\007 \002(" +
      "\t\022\023\n\013channelName\030\010 \002(\t\"k\n\027MSG_CG_CREATE_" +
      "CHARACTER\022\014\n\004name\030\001 \002(\t\022\016\n\006mainId\030\002 \002(\005\022" +
      "\013\n\003sex\030\003 \002(\005\022\014\n\004head\030\004 \002(\005\022\027\n\017systemFash" +
      "ionId\030\005 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_client_c2g_MSG_CG_USER_LOGIN_descriptor,
        new String[] { "AccountName", "Token", "Version", "DeviceId", "MainId", "RegisterId", "ChannelName", });
    internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_client_c2g_MSG_CG_CREATE_CHARACTER_descriptor,
        new String[] { "Name", "MainId", "Sex", "Head", "SystemFashionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
