 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.client.c2g;
import protocol.msgId.Id;
public class C2GIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(C2G.MSG_CG_USER_LOGIN.class, 0x110001);
          Id.getInst().SetMessage(C2G.MSG_CG_CREATE_CHARACTER.class, 0x110002);
     }
}
