 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.client.g2c;
import protocol.msgId.Id;
public class G2CIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(G2C.MSG_GC_USER_LOGIN.class, 0x210001);
     }
}
