// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: M2G.proto

package protocol.manager.gate;

public final class M2G {
  private M2G() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MSG_M2G_HEARTBEATOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.manager.gate.MSG_M2G_HEARTBEAT)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protocol.manager.gate.MSG_M2G_HEARTBEAT}
   */
  public  static final class MSG_M2G_HEARTBEAT extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.manager.gate.MSG_M2G_HEARTBEAT)
      MSG_M2G_HEARTBEATOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_M2G_HEARTBEAT.newBuilder() to construct.
    private MSG_M2G_HEARTBEAT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_M2G_HEARTBEAT() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_M2G_HEARTBEAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return M2G.internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return M2G.internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_M2G_HEARTBEAT.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_M2G_HEARTBEAT)) {
        return super.equals(obj);
      }
      MSG_M2G_HEARTBEAT other = (MSG_M2G_HEARTBEAT) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_M2G_HEARTBEAT parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2G_HEARTBEAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_M2G_HEARTBEAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2G_HEARTBEAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_M2G_HEARTBEAT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.manager.gate.MSG_M2G_HEARTBEAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.manager.gate.MSG_M2G_HEARTBEAT)
        MSG_M2G_HEARTBEATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_M2G_HEARTBEAT.class, Builder.class);
      }

      // Construct using protocol.manager.gate.M2G.MSG_M2G_HEARTBEAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor;
      }

      public MSG_M2G_HEARTBEAT getDefaultInstanceForType() {
        return MSG_M2G_HEARTBEAT.getDefaultInstance();
      }

      public MSG_M2G_HEARTBEAT build() {
        MSG_M2G_HEARTBEAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_M2G_HEARTBEAT buildPartial() {
        MSG_M2G_HEARTBEAT result = new MSG_M2G_HEARTBEAT(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_M2G_HEARTBEAT) {
          return mergeFrom((MSG_M2G_HEARTBEAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_M2G_HEARTBEAT other) {
        if (other == MSG_M2G_HEARTBEAT.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_M2G_HEARTBEAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_M2G_HEARTBEAT) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.manager.gate.MSG_M2G_HEARTBEAT)
    }

    // @@protoc_insertion_point(class_scope:protocol.manager.gate.MSG_M2G_HEARTBEAT)
    private static final MSG_M2G_HEARTBEAT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_M2G_HEARTBEAT();
    }

    public static MSG_M2G_HEARTBEAT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_M2G_HEARTBEAT>
        PARSER = new com.google.protobuf.AbstractParser<MSG_M2G_HEARTBEAT>() {
      public MSG_M2G_HEARTBEAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_M2G_HEARTBEAT(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_M2G_HEARTBEAT> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_M2G_HEARTBEAT> getParserForType() {
      return PARSER;
    }

    public MSG_M2G_HEARTBEAT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MSG_M2G_MAX_UIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.manager.gate.MSG_M2G_MAX_UID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();

    /**
     * <code>required string accountName = 2;</code>
     */
    boolean hasAccountName();
    /**
     * <code>required string accountName = 2;</code>
     */
    String getAccountName();
    /**
     * <code>required string accountName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>required int32 maxUid = 3;</code>
     */
    boolean hasMaxUid();
    /**
     * <code>required int32 maxUid = 3;</code>
     */
    int getMaxUid();

    /**
     * <code>required string channelName = 4;</code>
     */
    boolean hasChannelName();
    /**
     * <code>required string channelName = 4;</code>
     */
    String getChannelName();
    /**
     * <code>required string channelName = 4;</code>
     */
    com.google.protobuf.ByteString
        getChannelNameBytes();
  }
  /**
   * Protobuf type {@code protocol.manager.gate.MSG_M2G_MAX_UID}
   */
  public  static final class MSG_M2G_MAX_UID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.manager.gate.MSG_M2G_MAX_UID)
      MSG_M2G_MAX_UIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_M2G_MAX_UID.newBuilder() to construct.
    private MSG_M2G_MAX_UID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_M2G_MAX_UID() {
      result_ = 0;
      accountName_ = "";
      maxUid_ = 0;
      channelName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_M2G_MAX_UID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              accountName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxUid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              channelName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return M2G.internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return M2G.internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_M2G_MAX_UID.class, Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int ACCOUNTNAME_FIELD_NUMBER = 2;
    private volatile Object accountName_;
    /**
     * <code>required string accountName = 2;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string accountName = 2;</code>
     */
    public String getAccountName() {
      Object ref = accountName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accountName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAXUID_FIELD_NUMBER = 3;
    private int maxUid_;
    /**
     * <code>required int32 maxUid = 3;</code>
     */
    public boolean hasMaxUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 maxUid = 3;</code>
     */
    public int getMaxUid() {
      return maxUid_;
    }

    public static final int CHANNELNAME_FIELD_NUMBER = 4;
    private volatile Object channelName_;
    /**
     * <code>required string channelName = 4;</code>
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string channelName = 4;</code>
     */
    public String getChannelName() {
      Object ref = channelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channelName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      Object ref = channelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maxUid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, channelName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxUid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, channelName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_M2G_MAX_UID)) {
        return super.equals(obj);
      }
      MSG_M2G_MAX_UID other = (MSG_M2G_MAX_UID) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && (getResult()
            == other.getResult());
      }
      result = result && (hasAccountName() == other.hasAccountName());
      if (hasAccountName()) {
        result = result && getAccountName()
            .equals(other.getAccountName());
      }
      result = result && (hasMaxUid() == other.hasMaxUid());
      if (hasMaxUid()) {
        result = result && (getMaxUid()
            == other.getMaxUid());
      }
      result = result && (hasChannelName() == other.hasChannelName());
      if (hasChannelName()) {
        result = result && getChannelName()
            .equals(other.getChannelName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult();
      }
      if (hasAccountName()) {
        hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getAccountName().hashCode();
      }
      if (hasMaxUid()) {
        hash = (37 * hash) + MAXUID_FIELD_NUMBER;
        hash = (53 * hash) + getMaxUid();
      }
      if (hasChannelName()) {
        hash = (37 * hash) + CHANNELNAME_FIELD_NUMBER;
        hash = (53 * hash) + getChannelName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_M2G_MAX_UID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_MAX_UID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2G_MAX_UID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2G_MAX_UID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_M2G_MAX_UID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2G_MAX_UID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_M2G_MAX_UID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.manager.gate.MSG_M2G_MAX_UID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.manager.gate.MSG_M2G_MAX_UID)
        MSG_M2G_MAX_UIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_M2G_MAX_UID.class, Builder.class);
      }

      // Construct using protocol.manager.gate.M2G.MSG_M2G_MAX_UID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        maxUid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        channelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return M2G.internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor;
      }

      public MSG_M2G_MAX_UID getDefaultInstanceForType() {
        return MSG_M2G_MAX_UID.getDefaultInstance();
      }

      public MSG_M2G_MAX_UID build() {
        MSG_M2G_MAX_UID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_M2G_MAX_UID buildPartial() {
        MSG_M2G_MAX_UID result = new MSG_M2G_MAX_UID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxUid_ = maxUid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.channelName_ = channelName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_M2G_MAX_UID) {
          return mergeFrom((MSG_M2G_MAX_UID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_M2G_MAX_UID other) {
        if (other == MSG_M2G_MAX_UID.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000002;
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.hasMaxUid()) {
          setMaxUid(other.getMaxUid());
        }
        if (other.hasChannelName()) {
          bitField0_ |= 0x00000008;
          channelName_ = other.channelName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          return false;
        }
        if (!hasAccountName()) {
          return false;
        }
        if (!hasMaxUid()) {
          return false;
        }
        if (!hasChannelName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_M2G_MAX_UID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_M2G_MAX_UID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      private Object accountName_ = "";
      /**
       * <code>required string accountName = 2;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string accountName = 2;</code>
       */
      public String getAccountName() {
        Object ref = accountName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accountName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string accountName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accountName = 2;</code>
       */
      public Builder setAccountName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 2;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 2;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountName_ = value;
        onChanged();
        return this;
      }

      private int maxUid_ ;
      /**
       * <code>required int32 maxUid = 3;</code>
       */
      public boolean hasMaxUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 maxUid = 3;</code>
       */
      public int getMaxUid() {
        return maxUid_;
      }
      /**
       * <code>required int32 maxUid = 3;</code>
       */
      public Builder setMaxUid(int value) {
        bitField0_ |= 0x00000004;
        maxUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 maxUid = 3;</code>
       */
      public Builder clearMaxUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxUid_ = 0;
        onChanged();
        return this;
      }

      private Object channelName_ = "";
      /**
       * <code>required string channelName = 4;</code>
       */
      public boolean hasChannelName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string channelName = 4;</code>
       */
      public String getChannelName() {
        Object ref = channelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string channelName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getChannelNameBytes() {
        Object ref = channelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channelName = 4;</code>
       */
      public Builder setChannelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        channelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 4;</code>
       */
      public Builder clearChannelName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        channelName_ = getDefaultInstance().getChannelName();
        onChanged();
        return this;
      }
      /**
       * <code>required string channelName = 4;</code>
       */
      public Builder setChannelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        channelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.manager.gate.MSG_M2G_MAX_UID)
    }

    // @@protoc_insertion_point(class_scope:protocol.manager.gate.MSG_M2G_MAX_UID)
    private static final MSG_M2G_MAX_UID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_M2G_MAX_UID();
    }

    public static MSG_M2G_MAX_UID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_M2G_MAX_UID>
        PARSER = new com.google.protobuf.AbstractParser<MSG_M2G_MAX_UID>() {
      public MSG_M2G_MAX_UID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_M2G_MAX_UID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_M2G_MAX_UID> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_M2G_MAX_UID> getParserForType() {
      return PARSER;
    }

    public MSG_M2G_MAX_UID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tM2G.proto\022\025protocol.manager.gate\"\023\n\021MS" +
      "G_M2G_HEARTBEAT\"[\n\017MSG_M2G_MAX_UID\022\016\n\006re" +
      "sult\030\001 \002(\005\022\023\n\013accountName\030\002 \002(\t\022\016\n\006maxUi" +
      "d\030\003 \002(\005\022\023\n\013channelName\030\004 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_manager_gate_MSG_M2G_HEARTBEAT_descriptor,
        new String[] { });
    internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_manager_gate_MSG_M2G_MAX_UID_descriptor,
        new String[] { "Result", "AccountName", "MaxUid", "ChannelName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
