 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.manager.gate;
import protocol.msgId.Id;
public class M2GIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(M2G.MSG_M2G_HEARTBEAT.class, 0x310001);
          Id.getInst().SetMessage(M2G.MSG_M2G_MAX_UID.class, 0x310002);
     }
}
