 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.manager.relation;
import protocol.msgId.Id;
public class M2RIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.manager.relation.M2R.MSG_M2R_HEARTBEAT.class, 0x350001);
     }
}
