// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: M2Z.proto

package protocol.manager.zone;

public final class M2Z {
  private M2Z() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MSG_M2Z_HEARTBEATOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.manager.zone.MSG_M2Z_HEARTBEAT)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protocol.manager.zone.MSG_M2Z_HEARTBEAT}
   */
  public  static final class MSG_M2Z_HEARTBEAT extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.manager.zone.MSG_M2Z_HEARTBEAT)
      MSG_M2Z_HEARTBEATOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_M2Z_HEARTBEAT.newBuilder() to construct.
    private MSG_M2Z_HEARTBEAT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_M2Z_HEARTBEAT() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_M2Z_HEARTBEAT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_M2Z_HEARTBEAT.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_M2Z_HEARTBEAT)) {
        return super.equals(obj);
      }
      MSG_M2Z_HEARTBEAT other = (MSG_M2Z_HEARTBEAT) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_M2Z_HEARTBEAT parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2Z_HEARTBEAT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_M2Z_HEARTBEAT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2Z_HEARTBEAT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_M2Z_HEARTBEAT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.manager.zone.MSG_M2Z_HEARTBEAT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.manager.zone.MSG_M2Z_HEARTBEAT)
        MSG_M2Z_HEARTBEATOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_M2Z_HEARTBEAT.class, Builder.class);
      }

      // Construct using protocol.manager.zone.M2Z.MSG_M2Z_HEARTBEAT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor;
      }

      public MSG_M2Z_HEARTBEAT getDefaultInstanceForType() {
        return MSG_M2Z_HEARTBEAT.getDefaultInstance();
      }

      public MSG_M2Z_HEARTBEAT build() {
        MSG_M2Z_HEARTBEAT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_M2Z_HEARTBEAT buildPartial() {
        MSG_M2Z_HEARTBEAT result = new MSG_M2Z_HEARTBEAT(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_M2Z_HEARTBEAT) {
          return mergeFrom((MSG_M2Z_HEARTBEAT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_M2Z_HEARTBEAT other) {
        if (other == MSG_M2Z_HEARTBEAT.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_M2Z_HEARTBEAT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_M2Z_HEARTBEAT) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.manager.zone.MSG_M2Z_HEARTBEAT)
    }

    // @@protoc_insertion_point(class_scope:protocol.manager.zone.MSG_M2Z_HEARTBEAT)
    private static final MSG_M2Z_HEARTBEAT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_M2Z_HEARTBEAT();
    }

    public static MSG_M2Z_HEARTBEAT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_M2Z_HEARTBEAT>
        PARSER = new com.google.protobuf.AbstractParser<MSG_M2Z_HEARTBEAT>() {
      public MSG_M2Z_HEARTBEAT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_M2Z_HEARTBEAT(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_M2Z_HEARTBEAT> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_M2Z_HEARTBEAT> getParserForType() {
      return PARSER;
    }

    public MSG_M2Z_HEARTBEAT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MSG_M2Z_REPEAT_LOGINOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 characterUid = 1;</code>
     */
    boolean hasCharacterUid();
    /**
     * <code>required int32 characterUid = 1;</code>
     */
    int getCharacterUid();
  }
  /**
   * Protobuf type {@code protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN}
   */
  public  static final class MSG_M2Z_REPEAT_LOGIN extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN)
      MSG_M2Z_REPEAT_LOGINOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MSG_M2Z_REPEAT_LOGIN.newBuilder() to construct.
    private MSG_M2Z_REPEAT_LOGIN(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MSG_M2Z_REPEAT_LOGIN() {
      characterUid_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_M2Z_REPEAT_LOGIN(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              characterUid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MSG_M2Z_REPEAT_LOGIN.class, Builder.class);
    }

    private int bitField0_;
    public static final int CHARACTERUID_FIELD_NUMBER = 1;
    private int characterUid_;
    /**
     * <code>required int32 characterUid = 1;</code>
     */
    public boolean hasCharacterUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 characterUid = 1;</code>
     */
    public int getCharacterUid() {
      return characterUid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCharacterUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, characterUid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, characterUid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MSG_M2Z_REPEAT_LOGIN)) {
        return super.equals(obj);
      }
      MSG_M2Z_REPEAT_LOGIN other = (MSG_M2Z_REPEAT_LOGIN) obj;

      boolean result = true;
      result = result && (hasCharacterUid() == other.hasCharacterUid());
      if (hasCharacterUid()) {
        result = result && (getCharacterUid()
            == other.getCharacterUid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCharacterUid()) {
        hash = (37 * hash) + CHARACTERUID_FIELD_NUMBER;
        hash = (53 * hash) + getCharacterUid();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MSG_M2Z_REPEAT_LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MSG_M2Z_REPEAT_LOGIN prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN)
        MSG_M2Z_REPEAT_LOGINOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MSG_M2Z_REPEAT_LOGIN.class, Builder.class);
      }

      // Construct using protocol.manager.zone.M2Z.MSG_M2Z_REPEAT_LOGIN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        characterUid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return M2Z.internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor;
      }

      public MSG_M2Z_REPEAT_LOGIN getDefaultInstanceForType() {
        return MSG_M2Z_REPEAT_LOGIN.getDefaultInstance();
      }

      public MSG_M2Z_REPEAT_LOGIN build() {
        MSG_M2Z_REPEAT_LOGIN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MSG_M2Z_REPEAT_LOGIN buildPartial() {
        MSG_M2Z_REPEAT_LOGIN result = new MSG_M2Z_REPEAT_LOGIN(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.characterUid_ = characterUid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MSG_M2Z_REPEAT_LOGIN) {
          return mergeFrom((MSG_M2Z_REPEAT_LOGIN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MSG_M2Z_REPEAT_LOGIN other) {
        if (other == MSG_M2Z_REPEAT_LOGIN.getDefaultInstance()) return this;
        if (other.hasCharacterUid()) {
          setCharacterUid(other.getCharacterUid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCharacterUid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MSG_M2Z_REPEAT_LOGIN parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MSG_M2Z_REPEAT_LOGIN) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int characterUid_ ;
      /**
       * <code>required int32 characterUid = 1;</code>
       */
      public boolean hasCharacterUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 characterUid = 1;</code>
       */
      public int getCharacterUid() {
        return characterUid_;
      }
      /**
       * <code>required int32 characterUid = 1;</code>
       */
      public Builder setCharacterUid(int value) {
        bitField0_ |= 0x00000001;
        characterUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 characterUid = 1;</code>
       */
      public Builder clearCharacterUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        characterUid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN)
    }

    // @@protoc_insertion_point(class_scope:protocol.manager.zone.MSG_M2Z_REPEAT_LOGIN)
    private static final MSG_M2Z_REPEAT_LOGIN DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MSG_M2Z_REPEAT_LOGIN();
    }

    public static MSG_M2Z_REPEAT_LOGIN getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MSG_M2Z_REPEAT_LOGIN>
        PARSER = new com.google.protobuf.AbstractParser<MSG_M2Z_REPEAT_LOGIN>() {
      public MSG_M2Z_REPEAT_LOGIN parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_M2Z_REPEAT_LOGIN(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MSG_M2Z_REPEAT_LOGIN> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MSG_M2Z_REPEAT_LOGIN> getParserForType() {
      return PARSER;
    }

    public MSG_M2Z_REPEAT_LOGIN getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tM2Z.proto\022\025protocol.manager.zone\"\023\n\021MS" +
      "G_M2Z_HEARTBEAT\",\n\024MSG_M2Z_REPEAT_LOGIN\022" +
      "\024\n\014characterUid\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_manager_zone_MSG_M2Z_HEARTBEAT_descriptor,
        new String[] { });
    internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_manager_zone_MSG_M2Z_REPEAT_LOGIN_descriptor,
        new String[] { "CharacterUid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
