 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.manager.zone;
import protocol.msgId.Id;
public class M2ZIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.manager.zone.M2Z.MSG_M2Z_HEARTBEAT.class, 0x340001);
     }
}
