 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.manager.global;
import protocol.msgId.Id;
public class M2GMIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.manager.global.M2GM.MSG_M2GM_HEARTBEAT.class, 0x320001);
     }
}
