 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.zone.global;
import protocol.msgId.Id;
public class Z2GMIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(Z2GM.MSG_Z2GM_HEARTBEAT.class, 0x310001);
     }
}
