 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.barrack.manager;
import protocol.msgId.Id;
public class BRK2MIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.barrack.manager.BRK2M.MSG_BRK2M_HEARTBEAT.class, 0x630001);
     }
}
