 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
package protocol.gate.zone;
import protocol.msgId.Id;
public class G2ZIdGenerater{
     public static void GenerateId(){
          Id.getInst().SetMessage(protocol.gate.zone.G2Z.MSG_G2Z_HEARTBEAT.class, 0x140001);
     }
}
